CREATE TABLE `genres` (
  `id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `genreEN`	TEXT NOT NULL,
  `genreES`	TEXT NOT NULL
);

INSERT INTO genres ( genreEN, genreES ) VALUES ( "None", "Ninguno" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Blues", "Blues" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Classic Rock", "Rock clásico" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Country", "Country" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Dance", "Baile" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Disco", "Disco" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Funk", "Funk" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Grunge", "Grunge" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Hip-Hop", "Hip Hop" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Jazz", "Jazz" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Metal", "Metal" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "New Age", "New Age" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Oldies", "Oldies" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Other", "Otros" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Pop", "Pop" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "RnB", "RnB" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Rap", "Rap" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Reggae", "Reggae" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Rock", "Rock" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Techno", "Tecno" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Industrial", "Industrial" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Alternative", "Alternativa" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Ska", "Ska" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Death Metal", "Death Metal" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Pranks", "Pranks" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Soundtrack", "Banda sonora" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Euro-Techno", "Tecno europeo" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Ambient", "Ambiental" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Trip-Hop", "Trip Hop" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Vocal", "Vocal" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Jazz & Funk", "Jazz Funk" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Fusion", "Fusión" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Trance", "Trance" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Classical", "Clásica" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Instrumental", "Instrumental" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Acid", "Acid" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "House", "House" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Game", "Juegos" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Sound Clip", "Muestra de sonido" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Gospel", "Gospel" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Noise", "Ruido" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Alternative Rock", "Rock alternativo" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Bass", "Bajo" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Soul", "Soul" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Punk", "Punk" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Space", "Espacial" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Meditative", "Meditación" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Instrumental Pop", "Pop instrumental" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Instrumental Rock", "Rock instrumental" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Ethnic", "Ethnic" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Gothic", "Gótica" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Darkwave", "Darkwave" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Techno-Industrial", "Tecno industrial" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Electronic", "Electrónica" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Pop-Folk", "Pop Folk" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Eurodance", "Bailable europea" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Dream", "Dream" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Southern Rock", "Rock del sur" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Comedy", "Comedia" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Cult", "Culto" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Gangsta", "Gangsta" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Top 40", "Top 40" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Crhistian Rap", "Rap cristiano" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Pop Funk", "Pop Funk" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Jungle", "Jungle" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Native US", "Indio estadounidense" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Cabaret", "Cabaret" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "New Wave", "New Wave" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Psychedelic", "Psicodélica" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Rave", "Rave" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Show Tunes", "Showtunes" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Trailer", "Trailer" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Lo-Fi", "Lo Fi" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Tribal", "Tribal" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Acid Punk", "Acid Punk" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Acid Jazz", "Acid Jazz" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Polka", "Polka" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Retro", "Retro" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Musical", "Musical" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Rock", "Rock" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Rock ’n’ Roll", "RockNRoll" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Hard Rock", "Rock duro" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Folk", "Folk" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Folk-Rock", "Folk Rock" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "National Folk", "Rock nacional" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Swing", "Swing" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Fast Fusion", "Fusión rápida" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Bebop", "Bebop" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Latin", "Latina" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Revival", "Revival" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Celtic", "Celta" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Bluegrass", "Bluegrass" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Avantgarde", "Avantgarde" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Gothic Rock", "Rock gótico" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Progressive Rock", "Rock progresivo" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Psychedelic Rock", "Rock sicodélico" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Symphonic Rock", "Rock sinfónico" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Slow Rock", "Rock lento" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Big Band", "Grandes bandas" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Chorus", "Coral" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Easy Listening", "Suave" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Acoustic", "Acústica" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Humour", "Humorística" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Speech", "Discurso" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Chanson", "Chanson" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Opera", "Ópera" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Chamber Music", "Música de cámara" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Sonata", "Sonata" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Symphony", "Sinfónica" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Booty Bass", "Booty Bass" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Primus", "Primus" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Porn Groove", "Porn Groove" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Satire", "Satírica" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Slow Jamm", "Slow Jam" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Club", "Club" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Tango", "Tango" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Samba", "Samba" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Folklore", "Folklore" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Ballad", "Balada" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Power Ballad", "Balada rock" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Rhythmic Soul", "Rhythmic Soul" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Freestyle", "Estilo libre" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Duet", "Dúos" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Punk Rock", "Punk Rock" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Drum Solo", "Solo de batería" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "A Capella", "Acapella" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Euro-House", "House europea" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Dance Hall", "Salón de baile" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Goa", "Goa" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Drum & Bass", "Drum & Bass" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Club-House", "Club-House" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Hardcore Techno", "Tecno Hardcore" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Terror", "Terror" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Indie", "Indie" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "BritPop", "Pop Británico" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Negerpunk", "Negerpunk" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Polsk Punk", "Polsk Punk" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Beat", "Beat" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Christian Gangsta Rap", "Rap Cristiano Gangsta" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Heavy Metal", "Heavy Metal" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Black Metal", "Black Metal" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Crossover", "Crossover" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Contemporaary Christian", "Cristiana Contemporanea" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Christian Rock", "Rock Cristiano" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Merengue", "Merengue" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Salsa", "Salsa" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Thrash Metal", "Thrash Metal" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Anime", "Anime" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Jpop", "Jpop" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Synthpop", "Synthpop" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Abstract", "Abstracta" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Art Rock", "Art Rock" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Baroque", "Barroca" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Bhangra", "Bhangra" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Big Beat", "Big Beat" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Breakbeat", "Breakbeat" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Chillout", "Chillout" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Downtempo", "Downtempo" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Dub", "Dub" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "EBM", "EBM" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Eclectic", "Eclectic" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Electro", "Electro" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Electroclash", "Electroclash" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Emo", "Emo" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Experimental", "Experimental" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Garage", "Garaje" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Global", "Global" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "IDM", "IDM" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Illbient", "Maligno (Illbient)" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Industro-Goth", "Gótico Industrial" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Jam Band", "Jam Band" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Krautrock", "Krautrock" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Leftfield", "Leftfield" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Luonge", "" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Math Rock", "Rock Matemático" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "New Romantic", "Nueva Romántica" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Nu-Breakz", "Nu-Breakz" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Post-Punk", "Post-Punk" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Post-Rock", "Post-Rock" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Psytrance", "Psytrance" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Shoegaze", "Shoegaze" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Space Rock", "Rock Espacial" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Trop Rock", "Trop Rock" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "World Music", "Música del Mundo" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Neoclassical", "Neo Clásical" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Audiobook", "Audio Libro" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Audio Theatre", "Audio Teatro" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Neue Deutsche Welle", "Neue Deutsche Welle" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Podcast", "Podcast" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Indie-Rock", "Indie-Rock" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "G-Funk", "G-Funk" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Dubstep", "Dubstep" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Garage Rock", "Rock de Garaje" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Psybient", "Psybient" );
INSERT INTO genres ( genreEN, genreES ) VALUES ( "Nu-Metal", "Nu-Metal" );
